# Generated by Django 4.0.5 on 2022-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_author_name_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(help_text='e.g Buea Town', max_length=9),
        ),
    ]
